export type LootRarityKey = 'common' | 'uncommon' | 'rare' | 'very_rare' | 'legendary'
export type LootCategory = 'Arcana' | 'Armaments' | 'Implements' | 'Relics'

export interface LootTableEntry { range: string; item: string }
export type LootTable = Record<LootRarityKey, Record<LootCategory, LootTableEntry[]>>

export const LOOT_RARITY_LABELS: Record<LootRarityKey, string> = {
  common: 'Gewöhnlich',
  uncommon: 'Ungewöhnlich',
  rare: 'Selten',
  very_rare: 'Sehr selten',
  legendary: 'Legendär',
}

export function rollD100(): number { return Math.floor(Math.random() * 100) + 1 }
export function rollD4(): number { return Math.floor(Math.random() * 4) + 1 }

export function getItemFromTable(
  rarity: LootRarityKey,
  category: LootCategory,
  roll: number,
): string | null {
  const table = LOOT_TABLES[rarity][category]
  for (const entry of table) {
    const r = entry.range.trim()
    if (r === '####' || !r) continue
    if (r.includes('-')) {
      const parts = r.split('-')
      const min = parseInt(parts[0])
      const max = parseInt(parts[1] === '00' ? '100' : parts[1])
      if (!isNaN(min) && !isNaN(max) && roll >= min && roll <= max) return entry.item
    } else {
      const n = parseInt(r === '00' ? '100' : r)
      if (!isNaN(n) && roll === n) return entry.item
    }
  }
  return null
}

export const LOOT_CATEGORIES: { key: LootCategory; d4: number; emoji: string }[] = [
  { key: 'Arcana',     d4: 1, emoji: '🔮' },
  { key: 'Armaments',  d4: 2, emoji: '⚔️' },
  { key: 'Implements', d4: 3, emoji: '🛠️' },
  { key: 'Relics',     d4: 4, emoji: '✨' },
]

export const LOOT_TABLES: LootTable = {
  common: {
    Arcana: [
      { range: '1-4',   item: 'Wand of Smiles' },
      { range: '5-8',   item: 'Wand of Scowls' },
      { range: '9-12',  item: 'Cuddly Strixhaven Mascot' },
      { range: '13-16', item: 'Dark Shard Amulet' },
      { range: '17-20', item: 'Enduring Spellbook' },
      { range: '21-24', item: 'Feather Token (Feather Fall)' },
      { range: '25-28', item: 'Hat of Vermin' },
      { range: '29-32', item: 'Hat of Wizardry' },
      { range: '33-36', item: "Illuminator's Tattoo" },
      { range: '37-40', item: 'Imbued Wood Focus' },
      { range: '41-44', item: 'Keycharm' },
      { range: '45-48', item: 'Orb of Shielding' },
      { range: '49-52', item: 'Pipe of Rememberance' },
      { range: '53-56', item: 'Pipe of Smoke Monsters' },
      { range: '57-60', item: 'Rival Coin' },
      { range: '61-64', item: 'Ruby of the War Mage' },
      { range: '65-68', item: "Scribe's Pen" },
      { range: '69-72', item: 'Spellshard' },
      { range: '73-76', item: 'Staff of Adornment' },
      { range: '77-85', item: 'Wand of Pyrotechnics' },
      { range: '86-93', item: 'Clockwork Amulet' },
      { range: '94-00', item: 'Bottle of Boundless Coffee' },
    ],
    Armaments: [
      { range: '1-6',   item: 'Armor of Gleaming' },
      { range: '7-14',  item: 'Walloping Ammunition' },
      { range: '15-22', item: 'Cast-Off Armor' },
      { range: '24-30', item: 'Dread Helm' },
      { range: '31-38', item: 'Moon-Touched Sword' },
      { range: '39-46', item: 'Shield of Expression' },
      { range: '47-54', item: 'Silvered Weapon' },
      { range: '55-62', item: 'Smoldering Armor' },
      { range: '63-70', item: 'Sylvan Talon' },
      { range: '71-82', item: 'Unbreakable Arrow' },
      { range: '83-92', item: "Veteran's Cane" },
      { range: '93-00', item: 'Bottle of Boundless Coffee' },
    ],
    Implements: [
      { range: '1',     item: 'Band of Loyalty' },
      { range: '2-3',   item: 'Boots of False Tracks' },
      { range: '4-6',   item: 'Wand of Conducting' },
      { range: '7-9',   item: "Charlatan's Die" },
      { range: '10-12', item: 'Chest of Preserving' },
      { range: '13-15', item: 'Cleansing Stone' },
      { range: '16-18', item: 'Cloak of Billowing' },
      { range: '19-21', item: 'Cloak of Many Fashions' },
      { range: '22-24', item: 'Clothes of Mending' },
      { range: '25-27', item: 'Ear Horn of Hearing' },
      { range: '28-30', item: 'Ersatz Eye' },
      { range: '31-33', item: 'Everbright Lantern' },
      { range: '34-36', item: "Heward's Handy Spice Pouch" },
      { range: '37-39', item: 'Horn of Silent Alarm' },
      { range: '40-42', item: 'Instrument of Illusions' },
      { range: '43-45', item: 'Instrument of Scribing' },
      { range: '46-48', item: 'Lantern of Tracking' },
      { range: '49-51', item: 'Lock of Trickery' },
      { range: '52-54', item: 'Masque Charm' },
      { range: '55-57', item: 'Masquerade Tattoo' },
      { range: '58-60', item: 'Mystery Key' },
      { range: '61-63', item: 'Orb of Direction' },
      { range: '64-66', item: 'Orb of Gonging' },
      { range: '67-69', item: 'Orb of Time' },
      { range: '70-72', item: 'Pole of Collapsing' },
      { range: '73-75', item: 'Rope of Mending' },
      { range: '76-78', item: 'Shiftweave' },
      { range: '79-81', item: 'Spyglass of Clairvoyance' },
      { range: '82-84', item: 'Talking Doll' },
      { range: '85-87', item: 'Tankard of Plenty' },
      { range: '88-90', item: 'Tankard of Sobriety' },
      { range: '91-93', item: 'Thermal Cube' },
      { range: '94-00', item: 'Bottle of Boundless Coffee' },
    ],
    Relics: [
      { range: '1-7',   item: 'Wand of Smiles' },
      { range: '8-14',  item: 'Candle of the Deep' },
      { range: '15-21', item: 'Wand of Scowls' },
      { range: '22-28', item: 'Imbued Wood Focus' },
      { range: '29-35', item: 'Orb of Shielding' },
      { range: '36-42', item: 'Pole of Angling' },
      { range: '43-49', item: 'Rival Coin' },
      { range: '50-56', item: 'Ruby of the War Mage' },
      { range: '57',    item: "Scribe's Pen" },
      { range: '58-63', item: 'Staff of Adornment' },
      { range: '64-70', item: 'Staff of Birdcalls' },
      { range: '71-77', item: 'Staff of Flowers' },
      { range: '78-86', item: 'Wand of Pyrotechnics' },
      { range: '87-93', item: 'Clockwork Amulet' },
      { range: '94-00', item: 'Bottle of Boundless Coffee' },
    ],
  },
  uncommon: {
    Arcana: [
      { range: '1-4',   item: 'Spell Gem Lapis Lazuli' },
      { range: '5-8',   item: 'Enspelled Staff Cantrip' },
      { range: '9-12',  item: 'Medallion of Thoughts' },
      { range: '13-16', item: 'Amulet of Proof against Detection and Location' },
      { range: '17-20', item: 'Staff of the Adder' },
      { range: '21-24', item: 'Staff of the Python' },
      { range: '25-28', item: 'Spell Gem Obsidian' },
      { range: '29-32', item: 'Ring of Mind Shielding' },
      { range: '33-36', item: 'Eyes of Charming' },
      { range: '37-40', item: 'Circlet of Blasting' },
      { range: '41-44', item: 'Wind Fan' },
      { range: '45-48', item: 'Deck of Wonder' },
      { range: '49-52', item: "Ring of Puzzler's Wit" },
      { range: '53-56', item: 'Feywild Shard' },
      { range: '57-60', item: 'Mizzium Apparatus' },
      { range: '61-64', item: 'Brooch of Shielding' },
      { range: '65-68', item: 'Dragon-Touched Focus' },
      { range: '69-72', item: 'Enspelled Staff Level 1' },
      { range: '73-76', item: 'Skyblinder Staff' },
      { range: '77-80', item: 'Wand of Entagle' },
      { range: '81-84', item: 'Wand of Web' },
      { range: '85-88', item: 'Wand of Magic Missiles' },
      { range: '89-92', item: 'Pearl of Power' },
      { range: '93-96', item: 'Wand of the War Mage, +1' },
      { range: '97-00', item: 'Arcane Grimoire +1 / Bloodwell Vial +1 / Rod of the Pactkeeper +1' },
    ],
    Armaments: [
      { range: '1-3',   item: 'Ammunition, +1' },
      { range: '4-6',   item: 'Enspelled Armor Cantrip' },
      { range: '7-9',   item: 'Enspelled Weapon Cantrip' },
      { range: '10-12', item: 'Quiver of Ehlonna' },
      { range: '13-15', item: 'Adamantine Weapon' },
      { range: '16-18', item: 'Boomerang Shield' },
      { range: '19-21', item: 'Trident of Fish Command' },
      { range: '22-24', item: 'Sword of Vengeance' },
      { range: '25-27', item: 'Sling of Giant Felling' },
      { range: '28-30', item: 'Bracers of Archery' },
      { range: '31-33', item: 'Storm Boomerang' },
      { range: '34-36', item: "Mariner's Armor" },
      { range: '37-39', item: 'Coiling Grasp Tattoo' },
      { range: '40-42', item: 'Eldritch Claw Tattoo' },
      { range: '43-45', item: 'Javelin of Lightning' },
      { range: '46-48', item: 'Mithral Armor' },
      { range: '49-51', item: 'Dragonhide Belt, +1' },
      { range: '52-54', item: 'Bloodrage Greataxe' },
      { range: '55-57', item: "Crusader's Shortsword" },
      { range: '58-60', item: 'Sentinel Shield' },
      { range: '61-63', item: 'Serpent Scale Armor' },
      { range: '64-66', item: 'Armor of Weightlessness' },
      { range: '67-69', item: 'Enspelled Armor Level 1' },
      { range: '70-72', item: 'Enspelled Weapon Level 1' },
      { range: '73-75', item: 'Insignia of Claws' },
      { range: '76-78', item: "Plate of Knight's Fellowship" },
      { range: '79-81', item: 'Gauntlets of Ogre Power' },
      { range: '82-84', item: 'Weapon of Warning' },
      { range: '85-87', item: 'Shield, +1' },
      { range: '88-90', item: 'Adamantine Armor' },
      { range: '91-93', item: "Dragon's Wrath Weapon (Slumbering)" },
      { range: '94-00', item: 'Weapon, +1 / Wraps of Unarmed Power, +1' },
    ],
    Implements: [
      { range: '1',     item: "Baba Yaga's Dancing Broom" },
      { range: '2',     item: 'Balloon Pack' },
      { range: '3',     item: 'Wingwear' },
      { range: '4-5',   item: 'Eversmoking Bottle' },
      { range: '6',     item: 'Alchemy Jug' },
      { range: '7',     item: 'Emerald Pen' },
      { range: '8',     item: "Finder's Goggles" },
      { range: '9-10',  item: 'Bag of Tricks' },
      { range: '11',    item: 'Balance of Harmony' },
      { range: '12',    item: 'Circlet of Human Perfection' },
      { range: '13-14', item: 'Driftglobe' },
      { range: '15-16', item: 'Earworm' },
      { range: '17',    item: 'Decanter of Endless Water' },
      { range: '18-19', item: 'House of Cards' },
      { range: '20-22', item: 'Immovable Rod' },
      { range: '23',    item: 'Mask of the Beast' },
      { range: '24',    item: 'Living Gloves' },
      { range: '25',    item: 'Propeller Helm' },
      { range: '26',    item: 'Pipes of the Sewers' },
      { range: '27',    item: 'Pipes of Haunting' },
      { range: '28-29', item: 'Uncommon Glamerweave' },
      { range: '30-31', item: 'Wand of Secrets' },
      { range: '32-33', item: 'Wand of Magic Detection' },
      { range: '34-35', item: 'Eyes of the Eagle' },
      { range: '36-37', item: 'Eyes of Minute Seeing' },
      { range: '38',    item: 'Fabulist Gem' },
      { range: '39-40', item: 'Figure of Wondrous Power (Silver Raven)' },
      { range: '41-42', item: 'Prehistoric Figurine of Wondrous Power (Plesiosaurus)' },
      { range: '43',    item: 'Goggles of Night' },
      { range: '44',    item: 'Helm of Comprehending Languages' },
      { range: '45',    item: 'Helm of Telepathy' },
      { range: '46-47', item: 'Lantern of Revealing' },
      { range: '48',    item: 'Gem of Brightness' },
      { range: '49',    item: 'Cap of Water Breathing' },
      { range: '50',    item: 'Cloak of the Manta Ray' },
      { range: '51-52', item: 'Barrier Tattoo' },
      { range: '53',    item: 'Blasted Goggles' },
      { range: '54-55', item: 'Boots of Striding and Springing' },
      { range: '56-57', item: 'Gloves of Swimming and Climbing' },
      { range: '58-60', item: 'Pyroconvger' },
      { range: '61',    item: 'Ring of Jumping' },
      { range: '62',    item: 'Ring of Swimming' },
      { range: '63',    item: 'Ring of Truth Telling' },
      { range: '64-65', item: 'Ring of the Orator' },
      { range: '66',    item: 'Saddle of the Cavalier' },
      { range: '67-68', item: 'Rope of Climbing' },
      { range: '69',    item: 'Sensory Stone' },
      { range: '70',    item: 'Sending Stone' },
      { range: '71-72', item: 'Necklace of Adaptation' },
      { range: '73-74', item: 'Ring of Warmth' },
      { range: '75',    item: 'Headband of Intellect' },
      { range: '76-77', item: 'Slippers of Spider Climbing' },
      { range: '78',    item: "Spy's Murmur" },
      { range: '79',    item: "Card Sharp's Deck" },
      { range: '80',    item: 'Boots of the Winterlands' },
      { range: '81',    item: 'Broom of Flying' },
      { range: '82-83', item: 'Dragon Vessel (Slumbering)' },
      { range: '84-85', item: 'Gloves of Missile Snaring' },
      { range: '86',    item: 'Cloak of Elvenkind' },
      { range: '87',    item: 'Cloak of Protection' },
      { range: '88',    item: 'Gloves of Thievery' },
      { range: '89',    item: 'Hat of Disguise' },
      { range: '90-91', item: 'Scaled Ornament (Slumbering)' },
      { range: '92',    item: 'Stone of Good Luck' },
      { range: '93',    item: 'Winged Boots' },
      { range: '94',    item: 'Boots of Elvenkind' },
      { range: '95-96', item: 'Bag of Holding' },
      { range: '97-98', item: "Instrument of the Bards (Doss Lute / Fochlucan Bandore / Mac-Fuirmidh Cittern)" },
      { range: '99-00', item: 'All Purpose Tool, +1 / Rhythm Maker\'s Drum, +1' },
    ],
    Relics: [
      { range: '1-5',   item: 'Spell Gem Lapis Lazuli' },
      { range: '6-11',  item: 'Enspelled Staff Cantrip' },
      { range: '12-16', item: 'Staff of the Adder' },
      { range: '17-21', item: 'Staff of the Python' },
      { range: '22-27', item: 'Spell Gem (Lapis Lazuli)' },
      { range: '28-33', item: "Nature's Mantle" },
      { range: '34-39', item: 'Ring of Water Walking' },
      { range: '40-45', item: 'Periapt of Health' },
      { range: '46-50', item: 'Periapt of Wound Closure' },
      { range: '51-56', item: 'Pearl of Power' },
      { range: '57-62', item: 'Armor of the Fallen' },
      { range: '63-68', item: 'Armor of Fungal Spores' },
      { range: '69-74', item: 'Guardian Emblem' },
      { range: '75-80', item: 'Dragon-Touched Focus (Slumbering)' },
      { range: '81-86', item: 'Enspelled Staff 1st level' },
      { range: '86-91', item: 'Wand of the War Mage, +1' },
      { range: '92-00', item: 'Amulet of the Devout, +1 / Moon Sickle, +1' },
    ],
  },
  rare: {
    Arcana: [
      { range: '1-2',   item: 'Mirror of the Past' },
      { range: '3-4',   item: 'Wand of Winter' },
      { range: '5-6',   item: 'Staff of Charming' },
      { range: '7-8',   item: 'Astromancy Archive' },
      { range: '9-10',  item: 'Atlas of Endless Horizons' },
      { range: '11-12', item: 'Bowl of Commanding Water Elementals' },
      { range: '13-14', item: 'Brazier of Commanding Fire Elementals' },
      { range: '15-16', item: 'Censer of Controlling Air Elementals' },
      { range: '17-18', item: 'Claw of the Wyrm Rune' },
      { range: '19-20', item: 'Wand of Fear' },
      { range: '21-22', item: 'Deck of Oracles' },
      { range: '23-24', item: 'Scissors of Shadow Snipping' },
      { range: '25-26', item: 'Duplicitous Manuscript' },
      { range: '27-28', item: 'Elemental Essence Shard' },
      { range: '29-30', item: 'Far Realm Shard' },
      { range: '31-32', item: 'Staff of Ruling' },
      { range: '33-34', item: 'Wand of Paralysis' },
      { range: '35-36', item: 'Astral Shard' },
      { range: '37-38', item: 'Gulthias Staff' },
      { range: '39-40', item: "Heart Weaver's Primer" },
      { range: '41-42', item: 'Horn of Blasting' },
      { range: '43-44', item: "Iggwilv's Horn" },
      { range: '45-46', item: 'Libram of Souls and Flesh' },
      { range: '47-48', item: 'Alchemical Compendium' },
      { range: '49-50', item: 'Outer Essence Shard' },
      { range: '51-52', item: "Planecaller's Codex" },
      { range: '53-54', item: 'Protective Verses' },
      { range: '55-56', item: 'Wand of Binding' },
      { range: '57-58', item: 'Robe of Eyes' },
      { range: '59-60', item: 'Cube of Force' },
      { range: '61-62', item: 'Dragon-Touched Focus (Stirring)' },
      { range: '63-64', item: 'Shadowfell Shard' },
      { range: '65-66', item: 'Spell Gem (Bloodstone)' },
      { range: '67-68', item: 'Wand of Lightning Bolts' },
      { range: '69-70', item: 'Spider Staff' },
      { range: '71-72', item: 'Fulminating Treatise' },
      { range: '73-74', item: 'Staff of Defense' },
      { range: '75-76', item: 'Enspelled Staff Level 2' },
      { range: '77-78', item: 'Staff of the Rooted Hills' },
      { range: '79-80', item: 'Stone of Controlling Earth Elementals' },
      { range: '81-82', item: 'Sun Staff' },
      { range: '83-84', item: 'Ring of Spell Storing' },
      { range: '85-86', item: "Sage's Signet (Serpent / Songbird)" },
      { range: '87-88', item: 'Wand of Fireballs' },
      { range: '89-90', item: 'Spell Gem (Quartz)' },
      { range: '91-92', item: 'Enspelled Staff Level 3' },
      { range: '93-96', item: 'Wand of the War Mage, +2' },
      { range: '97-00', item: 'Arcane Grimoire +2 / Bloodwell Vial +2 / Rod of the Pactkeeper +2' },
    ],
    Armaments: [
      { range: '1',     item: 'Demon Skin' },
      { range: '2',     item: 'Staff of Withering' },
      { range: '3',     item: 'Armor of Vulnerability' },
      { range: '4-5',   item: 'Tentacle Rod' },
      { range: '6',     item: 'Giant Slayer' },
      { range: '7',     item: 'Banner of the Krig Rune' },
      { range: '8',     item: "Woodcutter's Axe" },
      { range: '9-10',  item: 'Berserker Axe' },
      { range: '11',    item: "Daern's Instant Fortress" },
      { range: '12',    item: "Gambler's Blade" },
      { range: '13-14', item: 'Claws of the Umber Hulk' },
      { range: '15-16', item: 'Mace of Disruption' },
      { range: '17',    item: 'Shield of Missile Attraction' },
      { range: '18-19', item: 'Feywrought Armor' },
      { range: '20-22', item: 'Gloomwrought Armor' },
      { range: '23',    item: 'Mace of Smiting' },
      { range: '24',    item: 'Ammunition, +2' },
      { range: '25',    item: "Donjon's Sundering Sphere" },
      { range: '26',    item: 'Dragon Slayer' },
      { range: '27',    item: 'Mace of Terror' },
      { range: '28-29', item: 'Luminous War Pick' },
      { range: '30-31', item: 'Crown of the Wrath Bringer' },
      { range: '32-33', item: 'Dragontooth Dagger' },
      { range: '34-35', item: 'Elven Chain' },
      { range: '36-37', item: "Dragon's Wrath Weapon (Stirring)" },
      { range: '38',    item: 'Two-Birds Sling' },
      { range: '39-40', item: 'Dagger of Venom' },
      { range: '41-42', item: 'War Horn of Valor' },
      { range: '43',    item: 'Bow of Conflagration' },
      { range: '44',    item: 'Flame Tongue' },
      { range: '45',    item: 'Bracer of Flying Daggers' },
      { range: '46-47', item: 'Gauntlets of Flaming Fury' },
      { range: '48',    item: 'Gavel of the Venn Rune' },
      { range: '49',    item: 'Arrow-Catching Shield' },
      { range: '50',    item: 'Glamoured Studded Leather' },
      { range: '51-52', item: 'Dragon Wing Bow' },
      { range: '53',    item: 'Dagger of Blindsight' },
      { range: '54-55', item: 'Grasping Whip' },
      { range: '56-57', item: 'Horn of Blasting' },
      { range: '58-60', item: 'Horn of Valhalla Silver' },
      { range: '61',    item: 'Horn of Valhalla Brass' },
      { range: '62',    item: 'Lash of Immolation' },
      { range: '63',    item: 'Leather Golem Armor' },
      { range: '64-65', item: 'Dragonhide Belt, +2' },
      { range: '66',    item: 'Enspelled Armor Level 2' },
      { range: '67-68', item: 'Enspelled Weapon Level 2' },
      { range: '69',    item: 'Glimmering Moonbow' },
      { range: '70',    item: 'Zephyr Armor' },
      { range: '71-72', item: 'Opal of the Ild Rune' },
      { range: '73-74', item: "Pariah's Shield" },
      { range: '75',    item: 'Ruinous Flail' },
      { range: '76-77', item: 'Scorpion Armor' },
      { range: '78',    item: "Serpent's Fang" },
      { range: '79',    item: 'Crystal Blade' },
      { range: '80',    item: 'Shield, +2' },
      { range: '81',    item: 'Armor of Resistance' },
      { range: '82-83', item: 'Starshot Crossbow' },
      { range: '84-85', item: 'Sun Blade' },
      { range: '86',    item: 'Sunforger' },
      { range: '87',    item: 'Sword of Life Stealing' },
      { range: '88',    item: 'Sword of Wounding' },
      { range: '89',    item: 'Armor, +1' },
      { range: '90-91', item: 'Enspelled Armor Level 3' },
      { range: '92',    item: 'Vicious Weapon' },
      { range: '93',    item: 'Voidwalker Armor' },
      { range: '94',    item: 'Enspelled Weapon Level 3' },
      { range: '95-96', item: 'Mizzium Armor' },
      { range: '97-00', item: 'Weapon, +2' },
    ],
    Implements: [
      { range: '1',     item: 'Portable Hole' },
      { range: '2',     item: 'Staff of Swarming Insects' },
      { range: '3',     item: "Hook of Fisher's Delight" },
      { range: '4-5',   item: 'Ventilating Lungs' },
      { range: '6',     item: 'Boots of Levitation' },
      { range: '7',     item: 'Feather of Diatryma Summoning' },
      { range: '8',     item: 'Bracers of Celerity' },
      { range: '9-10',  item: 'Rope of Entanglement' },
      { range: '11',    item: 'Bridle of Capturing' },
      { range: '12',    item: 'Ring of Animal Influence' },
      { range: '13-14', item: 'Cauldron of Plenty' },
      { range: '15-16', item: 'Wand of Enemy Detection' },
      { range: '17',    item: 'Cloak of the Bat' },
      { range: '18-19', item: 'Folding Boat' },
      { range: '20-22', item: "Galder's Bubble Pipe" },
      { range: '23',    item: 'Dimensional Shackles' },
      { range: '24',    item: 'Ring of Feather Falling' },
      { range: '25',    item: 'Eagle Whistle' },
      { range: '26',    item: 'Boots of Speed' },
      { range: '27',    item: 'Figurine of Wondrous Power (Bronze Griffon / Ebony Fly / Golden Lions / Ivory Goats / Marble Elephant / Onyx Dog / Serpentine Owl)' },
      { range: '28-29', item: 'Flying Chariot' },
      { range: '30-31', item: 'Cube of Summoning' },
      { range: '32-33', item: "Delver's Claws" },
      { range: '34-35', item: 'Gem of Seeing' },
      { range: '36-37', item: 'Ghost Lantern' },
      { range: '38',    item: 'Helm of Teleportation' },
      { range: '39-40', item: "Heward's Handy Haversack" },
      { range: '41-42', item: 'Barrier Tattoo' },
      { range: '43',    item: 'Horseshoes of Speed' },
      { range: '44',    item: "Wayfarer's Boots" },
      { range: '45',    item: 'Ioun Stone Awareness' },
      { range: '46-47', item: 'Robe of Summer' },
      { range: '48',    item: 'Ioun Stone Sustenance' },
      { range: '49',    item: 'Iron Bands of Bilarro' },
      { range: '50',    item: "Knave's Eye Patch" },
      { range: '51-52', item: 'Lyre of Building' },
      { range: '53',    item: 'Mantle of Spell Resistance' },
      { range: '54-55', item: 'Wand of Wonder' },
      { range: '56-57', item: 'Mizzium Mortar' },
      { range: '58-60', item: 'Molten Bronze Skin' },
      { range: '61',    item: 'Periapt of Proof Against Poison' },
      { range: '62',    item: 'Wings of Flying' },
      { range: '63',    item: 'Prehistoric Figurine of Wondrous Power (Kyanite Pteranodon)' },
      { range: '64-65', item: "Reveler's Concertina" },
      { range: '66',    item: 'Cape of the Mountebank' },
      { range: '67-68', item: 'Ring of Evasion' },
      { range: '69',    item: 'Dragon Vessel (Stirring)' },
      { range: '70',    item: 'Ring of Free Action' },
      { range: '71-72', item: 'Ring of Protection' },
      { range: '73-74', item: 'Ring of Resistance' },
      { range: '75',    item: 'Ring of the Ram' },
      { range: '76-77', item: 'Ring of X-Ray Vision' },
      { range: '78',    item: 'Ioun Stone Protection' },
      { range: '79',    item: 'Rod of Rulership' },
      { range: '80',    item: "Warrior's Passkey" },
      { range: '81',    item: 'Bracers of Defense' },
      { range: '82-83', item: 'Scaled Ornament (Stirring)' },
      { range: '84-85', item: 'Shadowfell Brand Tattoo' },
      { range: '86',    item: 'Shrieking Greaves' },
      { range: '87',    item: 'Siren Song Lyre' },
      { range: '88',    item: 'Staff of Healing' },
      { range: '89',    item: 'Belt of Dwarvenkind' },
      { range: '90-91', item: 'Amulet of Health' },
      { range: '92',    item: 'Cloak of Displacement' },
      { range: '93',    item: 'Wand of Viscid Globs' },
      { range: '94',    item: "Master's Amulet" },
      { range: '95-96', item: "Rogue's Mantle" },
      { range: '97-00', item: 'Ioun Stone Vitality' },
    ],
    Relics: [
      { range: '1-3',   item: 'Wand of Fear' },
      { range: '4-6',   item: 'Bell Branch' },
      { range: '7-9',   item: 'Bowl of Commanding Water Elementals' },
      { range: '10-12', item: 'Brazier of Commanding Fire Elementals' },
      { range: '13-15', item: 'Orb of the Stein Rune' },
      { range: '16-18', item: 'Censer of Controlling Air Elementals' },
      { range: '19-21', item: 'Charm of Plant Command' },
      { range: '22-24', item: 'Staff of Charming' },
      { range: '25-27', item: 'Kagonesti Forest Shroud' },
      { range: '28-30', item: 'Wand of Binding' },
      { range: '31-33', item: 'Enspelled Staff Level 2' },
      { range: '34-36', item: 'Wand of Paralysis' },
      { range: '37-39', item: 'Dragon-Touched Focus (Stirring)' },
      { range: '40-42', item: 'Stone of Controlling Earth Elementals' },
      { range: '43-45', item: 'Breastplate of Balance' },
      { range: '46-48', item: 'Staff of the Rooted Hills' },
      { range: '49-51', item: 'Scissors of Shadow Snipping' },
      { range: '52-54', item: "Devotee's Censer" },
      { range: '55-57', item: 'Spell Gem Bloodstone' },
      { range: '58-60', item: 'Staff of Ruling' },
      { range: '61-63', item: 'Ring of Spell Storing' },
      { range: '64-66', item: 'Staff of the Woodlands' },
      { range: '67-69', item: 'Necklace of Prayer Beads' },
      { range: '70-72', item: 'Sun Staff' },
      { range: '73-75', item: 'Staff of Healing' },
      { range: '76-78', item: 'Spell Gem Quartz' },
      { range: '79-81', item: "Fate Dealer's Deck, +1" },
      { range: '82-84', item: 'Enspelled Staff Level 3' },
      { range: '85-90', item: 'Wand of the War Mage, +2' },
      { range: '91-00', item: 'Amulet of the Devout, +2 / Moon Sickle, +2' },
    ],
  },
  very_rare: {
    Arcana: [
      { range: '1-3',   item: 'Wand of Polymorph (reroll)' },
      { range: '4-6',   item: 'Wand of Polymorph' },
      { range: '7-9',   item: 'Voyager Staff' },
      { range: '10-12', item: 'Crown of Whirling Comets' },
      { range: '13-15', item: 'Crystal Ball' },
      { range: '16-18', item: 'Crystalline Chronicle' },
      { range: '19-21', item: 'Deck of Dimensions' },
      { range: '22-24', item: 'Staff of Fire' },
      { range: '25-27', item: 'Staff of Thunder and Lightning' },
      { range: '28-30', item: 'Spell Gem Jade' },
      { range: '31-33', item: 'Spell Gem Topaz' },
      { range: '34-36', item: 'Hat of Many Spells' },
      { range: '37',    item: 'Spirit Board' },
      { range: '38-39', item: 'Ioun Stone Absorption' },
      { range: '40-41', item: 'Manual of Golems' },
      { range: '42-43', item: 'Mindblasting Cap' },
      { range: '44-45', item: 'Mirror of Life Trapping' },
      { range: '46-47', item: 'Mirror of Reflected Pasts' },
      { range: '48-49', item: 'Nimbus Coronet' },
      { range: '50',    item: 'Ring of Shooting Stars' },
      { range: '51-52', item: 'Ring of Telekinesis' },
      { range: '53-55', item: 'Robe of Scintillating Colors' },
      { range: '56-58', item: 'Robe of Stars' },
      { range: '59-61', item: 'Rod of Absorption' },
      { range: '62-64', item: 'Rod of Hellish Flames' },
      { range: '65-67', item: "Sage's Signet (Bear / Hart / Lion / Wolf)" },
      { range: '68-70', item: 'Skull Helm' },
      { range: '71-73', item: 'Spell Gem Amber' },
      { range: '74-76', item: 'Enspelled Staff Level 4' },
      { range: '77-79', item: 'Staff of Frost' },
      { range: '80',    item: 'Blast Scepter' },
      { range: '81-83', item: 'Staff of Fate' },
      { range: '83-85', item: 'Dragon-Touched Focus (Wakened)' },
      { range: '86-88', item: 'Deck of Wild Cards' },
      { range: '89-91', item: 'Enspelled Staff Level 5' },
      { range: '92',    item: 'Staff of Power' },
      { range: '93-95', item: "Illusionist's Bracers" },
      { range: '96-98', item: 'Wand of the War Mage, +3' },
      { range: '99-00', item: 'Arcane Grimoire +3 / Bloodwell Vial +3 / Rod of the Pactkeeper +3' },
    ],
    Armaments: [
      { range: '1',     item: 'Demon Armor' },
      { range: '2',     item: 'Animated Shield' },
      { range: '3-4',   item: 'Staff of Striking' },
      { range: '5',     item: 'Armor of Safeguarding' },
      { range: '6-7',   item: 'Sling Bullets of Althemone' },
      { range: '8',     item: 'Ammunition of Slaying' },
      { range: '9',     item: 'Javelin of Backbiting' },
      { range: '10',    item: 'Spear of Backbiting' },
      { range: '11',    item: 'Blade of the Medusa' },
      { range: '12',    item: 'Bloodseeker Ammunition' },
      { range: '13-14', item: 'Scimitar of Speed' },
      { range: '15-16', item: 'Bow of Melodies' },
      { range: '17-18', item: 'Clockwork Armor' },
      { range: '19-20', item: 'Dancing Sword' },
      { range: '21',    item: 'Ammunition, +3' },
      { range: '22',    item: 'Dragon Scale Mail' },
      { range: '23-24', item: 'Polymorph Blade' },
      { range: '25',    item: 'Sword of the Paruns' },
      { range: '26',    item: 'Dwarven Plate' },
      { range: '27',    item: 'Dwarven Thrower' },
      { range: '28',    item: "Dyrrn's Tentacle Whip" },
      { range: '29-30', item: 'Eldritch Staff' },
      { range: '31',    item: 'Elven Thrower' },
      { range: '32',    item: 'Enspelled Armor Level 4' },
      { range: '33-34', item: "Weapon of Throne's Command" },
      { range: '35',    item: 'Enspelled Weapon Level 4' },
      { range: '36-37', item: 'Tidecaller Trident' },
      { range: '38',    item: 'Energy Bow' },
      { range: '39-40', item: "Executioner's Axe" },
      { range: '41-42', item: "Fate Cutter's Shears" },
      { range: '43',    item: "Fool's Blade" },
      { range: '44',    item: 'Forcebreaker Weapon' },
      { range: '45-46', item: 'Frost Brand' },
      { range: '47-48', item: 'Hammer of Runic Focus' },
      { range: '49-50', item: "Heward's Hireling Armor" },
      { range: '51',    item: 'Stonemaker War Pick' },
      { range: '52',    item: 'Ingot of the Skold Rune' },
      { range: '53-54', item: 'Shield of the Cavalier' },
      { range: '55',    item: 'Living Armor' },
      { range: '56',    item: 'Lucent Destroyer' },
      { range: '57-58', item: 'Nine Lives Stealer' },
      { range: '59',    item: 'Thunderous Greatclub' },
      { range: '60-61', item: 'Quarterstaff of the Acrobat' },
      { range: '62-63', item: 'Sword of Sharpness' },
      { range: '64-65', item: 'Sapphire Buckler' },
      { range: '66-67', item: 'Bloodshed Blade' },
      { range: '68-69', item: 'Antimagic Armor' },
      { range: '70',    item: 'Shield of the Uven Rune' },
      { range: '71-72', item: 'Belt of Frost/Stone Giant Strength' },
      { range: '73-74', item: 'Oathbow' },
      { range: '75',    item: 'Horn of Valhalla Bronze' },
      { range: '76-77', item: 'Armor, +2' },
      { range: '78-79', item: "Dragon's Wrath Weapon (Wakened)" },
      { range: '80-81', item: 'Dragonhide Belt, +3' },
      { range: '82-83', item: 'Belt of Fire Giant Strength' },
      { range: '84-85', item: 'Spellguard Shield' },
      { range: '86-87', item: 'Thunderbuss' },
      { range: '88-89', item: 'Shield, +3' },
      { range: '90-91', item: 'Enspelled Weapon Level 5' },
      { range: '92',    item: 'Wyrmreaver Gauntlets' },
      { range: '93-94', item: 'Enspelled Armor Level 5' },
      { range: '95-00', item: 'Weapon, +3 / Wraps of Unarmed Power, +3' },
    ],
    Implements: [
      { range: '1-3',   item: "Tasha's Creeping Keelboat" },
      { range: '4-6',   item: 'Bobbing Lily Pad' },
      { range: '7-9',   item: 'Arcane Propulsion Arm' },
      { range: '10-12', item: 'Arcane Propulsion Arm (alt)' },
      { range: '13-15', item: 'Barrier Tattoo' },
      { range: '16-18', item: 'Amethyst Lodestone' },
      { range: '19-21', item: 'Helm of Brilliance' },
      { range: '22-24', item: 'Carpet of Flying' },
      { range: '25-27', item: 'Pennant of the Vind Rune' },
      { range: '28-30', item: 'Rod of Alertness' },
      { range: '31-33', item: 'Figurine of Wondrous Power (Obsidian Steed)' },
      { range: '34-36', item: 'Ghost Step Tattoo' },
      { range: '37',    item: 'Horseshoes of the Zephyr' },
      { range: '38-39', item: 'Cape of Enlargement' },
      { range: '40-41', item: 'Ioun Stone Agility' },
      { range: '42-43', item: 'Ioun Stone Fortitude' },
      { range: '44-45', item: 'Ioun Stone Insight' },
      { range: '46-47', item: 'Ioun Stone Intellect' },
      { range: '48-49', item: 'Ioun Stone Leadership' },
      { range: '50-51', item: 'Ioun Stone Strength' },
      { range: '52',    item: 'Ioun Stone of Vitality' },
      { range: '53-56', item: "Kyrzin's Ooze" },
      { range: '57-59', item: 'Lute of Thunderous Thumping' },
      { range: '60-63', item: 'Watchful Helm' },
      { range: '64-66', item: 'Mindguard Crown' },
      { range: '67-69', item: 'Mistral Mantle' },
      { range: '70-72', item: 'Shard of the Ise Rune' },
      { range: '73-75', item: 'Cloak of Arachnida' },
      { range: '76-78', item: 'Peregrine Mask' },
      { range: '79-81', item: 'Prehistoric Figurine of Wondrous Power (Carnelian Triceratops)' },
      { range: '82-84', item: 'Ring of Regeneration' },
      { range: '85-87', item: 'Dragon Vessel (Wakened)' },
      { range: '88',    item: 'Rod of Security' },
      { range: '89-91', item: 'Scaled Ornament (Wakened)' },
      { range: '92',    item: 'Absorbing Tattoo' },
      { range: '93-96', item: "All Purpose Tool, +3 / Rhythm-Maker's Drum, +3" },
      { range: '97-00', item: 'Ability Score Book (Manual of Bodily Health / Gainful Exercise / Quickness of Action / Tome of Clear Thought / Leadership & Influence / Understanding)' },
    ],
    Relics: [
      { range: '1-4',   item: 'Spirit Board' },
      { range: '5-8',   item: 'Cauldron of Rebirth' },
      { range: '9-12',  item: 'Crystal Ball' },
      { range: '13-16', item: 'Deck of Wild Cards' },
      { range: '17-20', item: 'Dragon-Touched Focus (Wakened)' },
      { range: '21-24', item: 'Spell Gem Jade' },
      { range: '25-28', item: 'Spell Gem Topaz' },
      { range: '29-32', item: 'Staff of Fate' },
      { range: '33-36', item: "Illusionist's Bracers" },
      { range: '37-40', item: 'Ioun Stone Absorption' },
      { range: '41-44', item: 'Lifewell Tattoo' },
      { range: '45-48', item: "Niko's Mace" },
      { range: '49-52', item: 'Nimbus Coronet' },
      { range: '53-56', item: 'Ring of Amity' },
      { range: '57-60', item: 'Rod of Absorption' },
      { range: '61-64', item: 'Rod of Hellish Flames' },
      { range: '65-68', item: 'Sanctum Amulet' },
      { range: '69-72', item: 'Skull Helm' },
      { range: '73-76', item: 'Spell Gem Amber' },
      { range: '77-80', item: 'Enspelled Staff Level 4' },
      { range: '81-84', item: 'Enspelled Staff Level 5' },
      { range: '85-87', item: 'Candle of Invocation' },
      { range: '88-90', item: "Fate Dealer's Deck, +2" },
      { range: '91-93', item: 'Staff of Thunder and Lightning' },
      { range: '94-96', item: 'Wand of the War Mage, +3' },
      { range: '97-00', item: 'Amulet of the Devout, +3 / Moon Sickle, +3' },
    ],
  },
  legendary: {
    Arcana: [
      { range: '1-3',   item: "Belashyrra's Beholder Crown" },
      { range: '4-6',   item: 'Crystal Ball of Mind Reading' },
      { range: '7-9',   item: 'Crystal Ball of Telepathy' },
      { range: '10-12', item: 'Crystal Ball of True Seeing' },
      { range: '13-15', item: 'Tome of the Stilled Tongue' },
      { range: '16-18', item: 'Well of Many Worlds' },
      { range: '19-21', item: 'Cubic Gate' },
      { range: '22-24', item: 'Rod of Lordly Might' },
      { range: '25-27', item: 'Spell Gem Diamond' },
      { range: '28-30', item: 'Spell Gem Ruby' },
      { range: '31-33', item: 'Spell Gem Star Ruby' },
      { range: '34-36', item: 'Helm of Disjunction' },
      { range: '37-39', item: 'Sphere of Annihilation' },
      { range: '40-42', item: 'Ioun Stone Greater Absorption' },
      { range: '43-45', item: "Jester's Mask" },
      { range: '46-48', item: 'Orb of Skoraeus' },
      { range: '49-51', item: 'Ring of Djinni Summoning' },
      { range: '52-54', item: 'Ring of Elemental Command' },
      { range: '55-57', item: 'Robe of the Archmagi' },
      { range: '58-60', item: 'Dragon-Touched Focus (Ascendant)' },
      { range: '61-63', item: 'Ruby Weave Gem' },
      { range: '64-66', item: 'Shard Solitaire' },
      { range: '67-69', item: 'Enspelled Staff Level 6' },
      { range: '70-72', item: 'Enspelled Staff Level 7' },
      { range: '73-75', item: 'Enspelled Staff Level 8' },
      { range: '76-78', item: 'Hither-Tither Staff' },
      { range: '79-81', item: 'Spindle of Fate' },
      { range: '82-84', item: 'Staff of the Magi' },
      { range: '85-87', item: 'Talisman of the Sphere' },
      { range: '88-90', item: 'Telescopic Transporter' },
      { range: '91-93', item: 'Deck of Many More Things' },
      { range: '94-00', item: 'Deck of Many Things' },
    ],
    Armaments: [
      { range: '1-3',   item: 'Armor of Invulnerability' },
      { range: '4-6',   item: 'Armor, +3' },
      { range: '7-9',   item: 'Sword of Answering' },
      { range: '10-12', item: 'Sword of the Planes' },
      { range: '13-15', item: 'Blood Fury Tattoo' },
      { range: '16-18', item: 'Defender' },
      { range: '19-21', item: "Dragon's Wrath Weapon (Ascendant)" },
      { range: '22-24', item: 'Enspelled Armor Level 6' },
      { range: '25-27', item: 'Enspelled Weapon Level 6' },
      { range: '28-30', item: 'Enspelled Armor Level 7' },
      { range: '31-33', item: 'Enspelled Weapon Level 7' },
      { range: '34-36', item: 'Enspelled Armor Level 8' },
      { range: '37-39', item: 'Enspelled Weapon Level 8' },
      { range: '40-42', item: 'Efreeti Chain' },
      { range: '43-45', item: "Euryale's Aegis" },
      { range: '46-48', item: 'Gloves of Soul Catching' },
      { range: '49-51', item: 'Greater Silver Sword' },
      { range: '52-54', item: 'Hammer of Thunderbolts' },
      { range: '55-57', item: 'Hazirawn' },
      { range: '58-60', item: 'Horn of Valhalla Iron' },
      { range: '61-63', item: 'Luck Blade' },
      { range: '64-66', item: 'Matalotok' },
      { range: '67-69', item: 'Moonblade' },
      { range: '70-72', item: 'Obsidian Flint Dragon Plate' },
      { range: '73-75', item: 'Plate Armor of Etherealness' },
      { range: '76-78', item: 'Powered Armor' },
      { range: '79-81', item: 'Shield of the Blazing Dreadnought' },
      { range: '82-84', item: "Stonebreaker's Breastplate" },
      { range: '85-87', item: 'Belt of Cloud Giant Strength' },
      { range: '88-90', item: 'Belt of Storm Giant Strength' },
      { range: '91-93', item: 'Topaz Annihilator' },
      { range: '94-00', item: 'Vorpal Sword' },
    ],
    Implements: [
      { range: '1-7',   item: 'Apparatus of Kwalish' },
      { range: '8-14',  item: 'Cloak of Invisibility' },
      { range: '15-21', item: 'Dragon Vessel (Ascendant)' },
      { range: '22-28', item: 'Gold Canary Figurine of Wondrous Power' },
      { range: '29-35', item: 'Harp of Gilded Plenty' },
      { range: '36-42', item: "Instrument of the Bards (Ollamh Harp)" },
      { range: '43-49', item: 'Scaled Ornament (Ascendant)' },
      { range: '50-56', item: 'Ioun Stone Regeneration' },
      { range: '57',    item: 'Iron Flask' },
      { range: '58-63', item: 'Lost Crown of Besilmer' },
      { range: '64-70', item: 'Prehistoric Figurine of Wondrous Power (Jasper T-Rex)' },
      { range: '71-77', item: 'Ring of Invisibility' },
      { range: '78-86', item: 'Ring of Spell Turning' },
      { range: '87-93', item: 'Ring of Three Wishes' },
      { range: '94-00', item: 'Ioun Stone Mastery' },
    ],
    Relics: [
      { range: '1-3',   item: "Belashyrra's Beholder Crown" },
      { range: '4-6',   item: 'Crystal Ball of Mind Reading' },
      { range: '7-9',   item: 'Crystal Ball of Telepathy' },
      { range: '10-12', item: 'Crystal Ball of True Seeing' },
      { range: '13-15', item: 'Dragon-Touched Focus (Ascendant)' },
      { range: '16-18', item: 'Spell Gem Diamond' },
      { range: '19-21', item: 'Spell Gem Ruby' },
      { range: '22-24', item: 'Spell Gem Star Ruby' },
      { range: '25-27', item: 'Fane-Eater' },
      { range: '28-30', item: 'Sphere of Annihilation' },
      { range: '31-33', item: 'Flail of Tiamat' },
      { range: '34-36', item: 'Holy Avenger' },
      { range: '37-39', item: 'Ioun Stone Greater Absorption' },
      { range: '40-42', item: 'Longbow of the Healing Hearth' },
      { range: '43-45', item: 'Nightbringer' },
      { range: '46-48', item: 'Orb of Skoraeus' },
      { range: '49-51', item: 'Platinum Scarf' },
      { range: '52-54', item: 'Rakdos Riteknife' },
      { range: '55-57', item: "Reaper's Scream" },
      { range: '58-60', item: 'Rod of Lordly Might' },
      { range: '61-63', item: 'Talisman of the Sphere' },
      { range: '64-66', item: 'Ruby Weave Gem' },
      { range: '67-69', item: 'Scarab of Protection' },
      { range: '70-72', item: 'Shard Solitaire' },
      { range: '73-75', item: 'Enspelled Staff Level 6' },
      { range: '76-78', item: 'Enspelled Staff Level 7' },
      { range: '79-81', item: 'Enspelled Staff Level 8' },
      { range: '82-84', item: "Fate Dealer's Deck, +3" },
      { range: '85-87', item: 'Spindle of Fate' },
      { range: '88-90', item: 'Talisman of Pure Good' },
      { range: '91-93', item: 'Talisman of Ultimate Evil' },
      { range: '94-00', item: 'Rod of Resurrection' },
    ],
  },
}
